platform :ios,'6.0'
pod 'Mantle', '~> 1.5.1'
pod 'FMDB', '~> 2.4'
pod 'Reachability', '~> 3.2'
pod 'AFNetworking', '~> 2.5.0'
pod 'MBProgressHUD', '~> 0.9'
pod 'SVProgressHUD', '~> 1.0'
pod 'Sculptor', '~> 0.3.0'
pod 'SDWebImage', '~> 3.7.1'
pod 'ReactiveCocoa', '~> 2.3.1'